### ISSUE TITLE
Views - Archived Challenges

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#665]
Link: https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c8a11c4ac70861db55d52

View:
![screen shot 2017-02-13 at 12 37 49](https://cloud.githubusercontent.com/assets/12638261/22883712/5d88c2ca-f1e9-11e6-96dc-84502ea51514.png)

**Comment by mk4111** [comment]
No line separating challenge cards --> this affects the class `.card` which is used throughout the app.
Will write up which views this impacts and whether we should (a) remove the bottom border from the .card class, and put it in a more relevant class, or (b) create a new class to attach to 'lists' or cards, so that no border is displayed (i.e. overwrite with `border: 0` ).

**Comment by mk4111** [comment]
Just had a quick scan through the wireframes - all views for explore + resources seem to have the same border seperating each of the cards.
Searching through `templates/` by 'card' (full match only), it seems that some of the views do not use `.card` class, and instead use `.list__item` (e.g. /organisations/browse view). Both classes use `border-bottom: #89a0ae 1px solid;` --> it might be good to unify these at some point...

@JMurphyWeb do you think now is a good time to 'refactor' for this? What are your thoughts?

**Comment by JMurphyWeb** [comment]
I can see why we would have two different classes for list items and cards. I haven't really looked into it but I don't think a refactor would be necessary? You may have a better idea of the benefits though.

**Comment by mk4111** [comment]
@JMurphyWeb - the .card class is being used in places other than the lists (explore views) too. As for why there's an overlap between .card and .list__item classes here, I'm not sure...

I'm not sure how worth it that is either, I know it'll affect orgs explore view, but I'll need to look into a bit more to make sure nothing else is affected. I think I will do this, if that's ok with you?

**Comment by JMurphyWeb** [comment]
```css
    .list__item {
        position: relative;
        padding: 1rem 8%;
        list-style: none;
        border-bottom: #89a0ae 1px solid;
    }

.card {
    padding: 4.25rem 1.75rem; /* 68px x 28px */
    text-align: center;
    color: #40667e;
    border-bottom: 1px solid #89a0ae;
    line-height: 1.5;
    position: relative;
}
```
